# Generated by Django 4.1 on 2022-11-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('user_type', models.CharField(choices=[('petani', 'PETANI'), ('pemda', 'PEMDA')], default='petani', max_length=6)),
                ('provinsi', models.CharField(choices=[('petani', 'PETANI'), ('pemda', 'PEMDA')], default='Aceh', max_length=38)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
