# Generated by Django 4.1 on 2022-11-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registerLogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerlogin',
            name='provinsi',
            field=models.CharField(choices=[('Aceh', 'ACEH'), ('Sumatra Utara', 'SUMATRA UTARA'), ('Sumatra Barat', 'SUMATRA BARAT'), ('Riau', 'RIAU'), ('Kepulauan Seribu', 'KEPULAUAN RIAU'), ('Jambi', 'JAMBI'), ('Bengkulu', 'BENGKULU'), ('Sumatra Selatan', 'SUMATRA SELATAN'), ('Kepulauan Bangka Belitung', 'KEPULAUAN BANGKA BELITUNG'), ('Lampung', 'LAMPUNG'), ('Banten', 'BANTEN'), ('DKI Jakarta', 'DKI JAKARTA'), ('Jawa Barat', 'JAWA BARAT'), ('Jawa Tengah', 'JAWA TENGAH'), ('Daerah Istimewa Yogyakarta', 'DAERAH ISTIMEWA YOGYAKARTA'), ('Jawa Timur', 'JAWA TIMUR'), ('Bali', 'BALI'), ('Nusa Tenggara Barat', 'NUSA TENGGARA BARAT'), ('Nusa Tenggara Timur', 'NUSA TENGGARA TIMUR'), ('Kalimantan Barat', 'KALIMANTAN BARAT'), ('Kalimantan Tengah', 'KALIMANTAN TENGAH'), ('Kalimantan Selatan', 'KALIMANTAN SELATAN'), ('Kalimantan Timur', 'KALIMANTAN TIMUR'), ('Kalimantan Utara', 'KALIMANTAN UTARA'), ('Sulawesi Barat', 'SULAWESI BARAT'), ('Sulawesi Selatan', 'SULAWESI SELATAN'), ('Sulawesi Tenggara', 'SULAWESI TENGGARA'), ('Sulawesi Tengah', 'SULAWESI TENGAH'), ('Gorontalo', 'GORONTALO'), ('Sulawesi Utara', 'SULAWESI UTARA'), ('Maluku Utara', 'MALUKU UTARA'), ('Maluku', 'MALUKU'), ('Papua', 'PAPUA'), ('Papua Tengah', 'PAPUA TENGAH'), ('Papua Pegunungan', 'PAPUA PEGUNUNGAN'), ('Papua Selatan', 'PAPUA SELATAN')], default='Aceh', max_length=38),
        ),
    ]
