# Generated by Django 4.1 on 2022-11-01 00:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('add_item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangPetani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=255)),
                ('kuantitas_barang', models.BigIntegerField()),
                ('daerah_asal', models.CharField(default='Jakarta', max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
