# Generated by Django 4.1 on 2022-11-02 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_item', '0002_barangpetani_delete_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BarangWishlist',
        ),
    ]
