# Generated by Django 4.1 on 2022-10-29 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('req_item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='govreqitem',
            name='user_gov',
        ),
    ]
