# Generated by Django 4.1 on 2022-10-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_item', '0002_remove_govreqitem_user_gov'),
    ]

    operations = [
        migrations.AddField(
            model_name='govreqitem',
            name='closed_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
