# Generated by Django 4.1 on 2022-10-30 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('req_item', '0003_govreqitem_closed_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='govreqitem',
            old_name='closed_date',
            new_name='request_date',
        ),
    ]
