# Generated by Django 4.1 on 2022-10-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req_item', '0004_rename_closed_date_govreqitem_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govreqitem',
            name='request',
            field=models.CharField(max_length=50),
        ),
    ]
