# Generated by Django 4.1 on 2022-10-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('item_amount', models.IntegerField()),
                ('request_date', models.DateField(null=True)),
                ('closed_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
