# Generated by Django 4.1 on 2022-10-29 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pemda_home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='request_date',
        ),
    ]
