# Generated by Django 4.1 on 2022-10-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemda_home', '0003_orderhistory_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='item_amount',
            field=models.IntegerField(default=0),
        ),
    ]
