# Generated by Django 4.1 on 2022-10-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemda_home', '0005_alter_orderhistory_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='review',
            field=models.TextField(default=''),
        ),
    ]
